services:

  likec4-dev-poc:
    build:
      context: ./likec4
    image: otus-aia/likec4:local
    working_dir: /data
    init: true
    ipc: host
    ports:
      - "5173:5173"
      - "24678:24678"
    environment:
      CHOKIDAR_USEPOLLING: "1"
      CHOKIDAR_INTERVAL: "200"
    volumes:
      - ../architecture/poc:/data
      - ../docs/diagrams/poc:/data/assets
    command: ["start", "--host", "0.0.0.0"]

  likec4-dev-mvp:
    image: otus-aia/likec4:local
    working_dir: /data
    init: true
    ipc: host
    ports:
      - "5174:5173"
      - "24679:24678"
    environment:
      CHOKIDAR_USEPOLLING: "1"
      CHOKIDAR_INTERVAL: "200"
    volumes:
      - ../architecture/mvp:/data
      - ../docs/diagrams/mvp:/data/assets
    command: ["start", "--host", "0.0.0.0"]
